#!/usr/bin/env python

import sys

sys.path.append("/usr/lib/solusos/config/")

try:
	import gobject
	from configservice import ConfigService
	from dbus.mainloop.glib import DBusGMainLoop
except:
	sys.exit(1)


''' Start the ConfigService on D-BUS '''
if __name__ == '__main__':
	loop = gobject.MainLoop()
	try:

		service = ConfigService(loop)
		loop.run()
	finally:
		loop.quit()
	sys.exit(0)
